cls_token: false
d_model: 512
dropout: 0.1
encoder_type: dense
lr: 0.0001
multiply_by_expr: false
n_genes: 2000
n_heads: 8
n_layers: 6
outdir: contrastive/runs/contrastive_dense_d512_l6_t1.0_05-08-19:56
temperature: 1.0
